dialects:
  nigeria:
  - following_context: $
    preceding_context: ''
    replacement: s
    segment: 'z'
  - following_context: ''
    preceding_context: '^'
    replacement: ''
    segment: 'ç'
  - following_context: ''
    preceding_context: '^'
    replacement: ''
    segment: 'h'
  - following_context: '$'
    preceding_context: 'ŋ'
    replacement: ''
    segment: 'ɡ'
  uk:
  - following_context: ''
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ʔ
    segment: 't[ʲʷ]?'
  - following_context: ʉː?
    preceding_context: ''
    replacement: tʃ
    segment: 'tʲ'
  - following_context: ʉː?
    preceding_context: ''
    replacement: dʒ
    segment: 'dʲ'
  - following_context: ''
    preceding_context: '^'
    replacement: ''
    segment: 'ç'
  - following_context: ''  # mitten glottalized syllabic
    preceding_context: ''
    replacement: ʔ n̩
    segment: t ə n
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic n
    preceding_context: ''
    replacement: n̩
    segment: ə n
  - following_context: $  # syllabic n
    preceding_context: ''
    replacement: n̩
    segment: ə n
  - following_context: $  # syllabic m
    preceding_context: ''
    replacement: m̩
    segment: ə m
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic m
    preceding_context: ''
    replacement: m̩
    segment: ə m
  - following_context: $  # syllabic l
    preceding_context: ''
    replacement: ɫ̩
    segment: ə ɫ
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic l
    preceding_context: ''
    replacement: ɫ̩
    segment: ə ɫ
  - following_context: '[ɪi]ː?'  # th-fronting
    preceding_context: ''
    replacement: fʲ
    segment: 'θ'
  - following_context: '[^ɪi]+'  # th-fronting
    preceding_context: ''
    replacement: f
    segment: 'θ'
  - following_context: '$'  # th-fronting
    preceding_context: ''
    replacement: f
    segment: 'θ'
  - following_context: '[ɪi]ː?'  # th-fronting
    preceding_context: ''
    replacement: vʲ
    segment: 'ð'
  - following_context: '[^ɪi]+'  # th-fronting
    preceding_context: ''
    replacement: v
    segment: 'ð'
  - following_context: '$'  # th-fronting
    preceding_context: ''
    replacement: v
    segment: 'ð'
  india:
  - following_context: ''
    preceding_context: ''
    replacement: ɾ
    segment: 'ɹ'
  - following_context: ''
    preceding_context: ''
    replacement: a
    segment: 'ɒ'
  - following_context: ''
    preceding_context: ''
    replacement: a
    segment: 'ɑ'
  - following_context: ''
    preceding_context: ''
    replacement: aː
    segment: 'ɒː'
  - following_context: ''
    preceding_context: ''
    replacement: aː
    segment: 'ɑː'
  - following_context: ''
    preceding_context: ''
    replacement: f
    segment: 'pʰ'
  - following_context: ''
    preceding_context: ''
    replacement: dʒ
    segment: 'z'
  - following_context: ''
    preceding_context: ''
    replacement: dʒ
    segment: 'ʒ'
  - following_context: ''
    preceding_context: ''
    replacement: z
    segment: 'ʒ'
  - following_context: ''
    preceding_context: ''
    replacement: ʃ
    segment: 'ʒ'
  us:
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾ
    segment: '[td]'
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: ɹ
    replacement: ɾ
    segment: '[td]'
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: ɫ
    replacement: ɾ
    segment: '[td]'
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾʲ
    segment: '[td]ʲ'
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: ɹ
    replacement: ɾʲ
    segment: '[td]ʲ'
  - following_context: (ɪ|ə|ɚ|i)  # t/d flapping
    preceding_context: ɫ
    replacement: ɾʲ
    segment: '[td]ʲ'
  - following_context: (ɪ|ə|ɚ|i)  # nasal flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾ̃
    segment: (ɲ|n)
  - following_context: (ɪ|ə|ɚ|i)  # nasal flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾ̃
    segment: (ɲ|n) [td][ʲʷ]?
  - following_context: $  # caught-cot merger
    preceding_context: ''
    replacement: ɑː
    segment: ɒː
  - following_context: '[^ɹ]'  # caught-cot merger
    preceding_context: ''
    replacement: ɑː
    segment: ɒː
  - following_context: $  # caught-cot merger
    preceding_context: ''
    replacement: ɑ
    segment: ɒ
  - following_context: '[^ɹ]'  # caught-cot merger
    preceding_context: ''
    replacement: ɑ
    segment: ɒ
  - following_context: $  # t/d flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾ
    segment: t
  - following_context: $  # t glottalization
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ʔ
    segment: t
  - following_context: $  # t deletion
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ''
    segment: t
  - following_context: $  # t/d flapping
    preceding_context: (ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
    replacement: ɾ
    segment: d
  - following_context: '[nmŋɱɲ]ʲ?'  # pin-pen merger
    preceding_context: ''
    replacement: ɪ
    segment: ɛ
  - following_context: '(ɫ|ɫ̩)'  # fill-feal merger
    preceding_context: ''
    replacement: ɪ
    segment: iː?
  - following_context: '(ɫ|ɫ̩)'  # fail-fell merger
    preceding_context: ''
    replacement: ɛ
    segment: ej
  - following_context: '(ɫ|ɫ̩)'  # boil-ball merger
    preceding_context: ''
    replacement: ɒː
    segment: ɔj
  - following_context: 'n'  # z-stopping
    preceding_context: ''
    replacement: d
    segment: z
  - following_context: '$'  # schwa for final ow
    preceding_context: ''
    replacement: ə
    segment: ow
  - following_context: ''  # non-rhotic dialects
    preceding_context: ''
    replacement: ə
    segment: ɚ
  - following_context: ''  # non-rhotic dialects
    preceding_context: ''
    replacement: ɜː
    segment: ɝ
  - following_context: '[tpkcsʃf][ʲʷ]?'  # price monophthongization
    preceding_context: ''
    replacement: aː
    segment: aj
  - following_context: ɡ  # bag raising
    preceding_context: ''
    replacement: ej
    segment: æ
  - following_context: ɡ  # beg raising
    preceding_context: ''
    replacement: ej
    segment: ɛ
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # non-rhotic dialects
    preceding_context: '(ʊ|ɛ|ɒ|ɪ|ɑ)'
    replacement: ə
    segment: ɹ
  - following_context: '$'  # non-rhotic dialects
    preceding_context: '(ʊ|ɛ|ɒ|ɪ|ɑ)'
    replacement: ə
    segment: ɹ
  - following_context: ''  # mitten glottalized syllabic
    preceding_context: ''
    replacement: ʔ n̩
    segment: t ə n
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic n
    preceding_context: ''
    replacement: n̩
    segment: ə n
  - following_context: $  # syllabic n
    preceding_context: ''
    replacement: n̩
    segment: ə n
  - following_context: $  # syllabic m
    preceding_context: ''
    replacement: m̩
    segment: ə m
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic m
    preceding_context: ''
    replacement: m̩
    segment: ə m
  - following_context: $  # syllabic l
    preceding_context: ''
    replacement: ɫ̩
    segment: ə ɫ
  - following_context: '[^ʊɔɝaɛeoæɐɪəɚɑʉɒi].*'  # syllabic l
    preceding_context: ''
    replacement: ɫ̩
    segment: ə ɫ
  - following_context: '[ɪi]ː?'  # th-fronting
    preceding_context: ''
    replacement: fʲ
    segment: 'θ'
  - following_context: '[^ɪi]+'  # th-fronting
    preceding_context: ''
    replacement: f
    segment: 'θ'
  - following_context: '$'  # th-fronting
    preceding_context: ''
    replacement: f
    segment: 'θ'
  - following_context: '[ɪi]ː?'  # th-fronting
    preceding_context: ''
    replacement: vʲ
    segment: 'ð'
  - following_context: '[^ɪi]+'  # th-fronting
    preceding_context: ''
    replacement: v
    segment: 'ð'
  - following_context: '$'  # th-fronting
    preceding_context: ''
    replacement: v
    segment: 'ð'
rules:
- following_context: .*(ʊ|ɔj|ɝ|ɛ|ej|ow|æ|aw|aj|ɐ|ɪ|ə|ɚ|ɑ|ʉ|ɒ|i)ː?
  preceding_context: ^
  replacement: ''
  segment: ə
- following_context: $
  preceding_context: '[sʃn]'
  replacement: ''
  segment: t
- following_context: $
  preceding_context: '[zʒn]'
  replacement: ''
  segment: d
- following_context: ''
  preceding_context: 'n'
  replacement: ''
  segment: d
- following_context: ə|ɚ
  preceding_context: ''
  replacement: j
  segment: i
- following_context: ə|ɚ
  preceding_context: ''
  replacement: w
  segment: ʉ
- following_context: '$'
  preceding_context: ''
  replacement: t̪
  segment: 't θ'
- following_context: ''
  preceding_context: ''
  replacement: t̪
  segment: 'θ t'
- following_context: '$'
  preceding_context: ''
  replacement: d̪
  segment: 'ð d'
- following_context: ''
  preceding_context: ''
  replacement: d̪
  segment: 'd ð'
- following_context: ''
  preceding_context: ''
  replacement: d̪
  segment: ð
- following_context: ''
  preceding_context: ''
  replacement: t̪
  segment: θ
- following_context: '[tpkcsʃf][ʲʷ]?'
  preceding_context: ''
  replacement: s
  segment: z
- following_context: '[tpkcsʃf][ʲʷ]?'
  preceding_context: ''
  replacement: t
  segment: d
- following_context: '[tpkcsʃf][ʲʷ]?'
  preceding_context: ''
  replacement: p
  segment: b
- following_context: '[tpkcsʃf][ʲʷ]?'
  preceding_context: ''
  replacement: k
  segment: ɡ
- following_context: '[tpkcsʃf][ʲʷ]?'
  preceding_context: ''
  replacement: tʃ
  segment: dʒ
- following_context: '[vf]ʲ?'
  preceding_context: ''
  replacement: ɱ
  segment: m
- following_context: '[vf]ʲ?'
  preceding_context: ''
  replacement: ɱ
  segment: 'n'
- following_context: '[td]$'
  preceding_context: m
  replacement: ''
  segment: '[pb]'
- following_context: '[sz]$'
  preceding_context: 'n'
  replacement: ''
  segment: '[td]'
- following_context: '[s]$'
  preceding_context: ''
  replacement: k
  segment: '[sʃ] k'
- following_context: '[s]$'
  preceding_context: ''
  replacement: ''
  segment: '[sʃ] t'
- following_context: $  # ask metathesis
  preceding_context: ''
  replacement: k s
  segment: s k
- following_context: '[dtcɟɡk][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: p
- following_context: '[pbcɟɡk][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: t
- following_context: '[pbcɟɡk][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: d
- following_context: '[dtcɟɡk][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: b
- following_context: '[dtpb][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: k
- following_context: '[dtpb][ʲʷ]?'
  preceding_context: ''
  replacement: ''
  segment: ɡ
- following_context: ([tpkc][ʲʷ]?)? ɹ
  preceding_context: ''
  replacement: ʃ
  segment: s
- following_context: ''
  preceding_context: ''
  replacement: tʃ
  segment: t[ʲʷ]? ɹ
- following_context: ''
  preceding_context: ''
  replacement: dʒ
  segment: d[ʲʷ]? ɹ
- following_context: ə n
  preceding_context: ''
  replacement: ʔ
  segment: t
- following_context: $  # ing/in' variation
  preceding_context: ɪ
  replacement: 'n'
  segment: ŋ
- following_context: z $  # ing/in' variation
  preceding_context: ɪ
  replacement: 'n'
  segment: ŋ
- following_context: ''  # non-native accents
  preceding_context: ''
  replacement: z
  segment: 'ð'
- following_context: ''  # non-native accents
  preceding_context: ''
  replacement: s
  segment: 'θ'
- following_context: ''  # schwa deletion
  preceding_context: ''
  replacement: l ə
  segment: 'ə l ə'
- following_context: ''  # schwa deletion
  preceding_context: ''
  replacement: ʎ ə
  segment: 'ə ʎ ə'
- following_context: ''  # schwa deletion
  preceding_context: ''
  replacement: n ə
  segment: 'ə n ə'
- following_context: ''  # schwa deletion
  preceding_context: ''
  replacement: m ə
  segment: 'ə m ə'
- following_context: ''  # schwa deletion
  preceding_context: ''
  replacement: ɹ ə
  segment: 'ə ɹ ə'
