rules:
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'i̥'
  segment: i
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: i
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'i̥'
  segment: i
- following_context: '$'
  preceding_context: ''
  replacement: 'eː'
  segment: 'a i'
- following_context: '$'
  preceding_context: ''
  replacement: 'nː a i'
  segment: 'ɾ a n a i'
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: i
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɯ̥'
  segment: ɯ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɯ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɯ̥'
  segment: ɯ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɯ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɨ̥'
  segment: ɨ
- following_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɨ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: 'ɨ̥'
  segment: ɨ
- following_context: '$'
  preceding_context: '[skctɕɸçhp][ʲsɕ]?ː?'
  replacement: ''
  segment: ɨ
- following_context: ''
  preceding_context: '^'
  replacement: 'z'
  segment: dz
- following_context: ''
  preceding_context: '^'
  replacement: 'ʑ'
  segment: dʑ
- following_context: '$'
  preceding_context: ''
  replacement: 'm'
  segment: ɴ
- following_context: '$'
  preceding_context: ''
  replacement: 'n'
  segment: ɴ
- following_context: '$'
  preceding_context: ''
  replacement: 'ɲ'
  segment: ɴ
- following_context: '$'
  preceding_context: ''
  replacement: 'ŋ'
  segment: ɴ
- following_context: '$'
  preceding_context: ''
  replacement: 'ɰ̃'
  segment: ɴ
