rules:
- following_context: ''
  preceding_context: ''
  replacement: ''
  segment: ʔ
- following_context: ''
  preceding_context: ''
  replacement: ''
  segment: ɻ
- following_context: ''
  preceding_context: ''
  replacement: 'mʲ'
  segment: 'm j'
- following_context: ''
  preceding_context: ''
  replacement: 'ʎ'
  segment: 'l j'
- following_context: ''
  preceding_context: ''
  replacement: 'ɲ'
  segment: 'n j'
- following_context: ''
  preceding_context: ''
  replacement: 'tʲ'
  segment: 'tʰ j'
- following_context: ''
  preceding_context: ''
  replacement: 'tʲ'
  segment: 't j'
- following_context: ''
  preceding_context: ''
  replacement: 'pʲ'
  segment: 'pʰ j'
- following_context: ''
  preceding_context: ''
  replacement: 'pʲ'
  segment: 'p j'
- following_context: ''
  preceding_context: ''
  replacement: 'pʷ'
  segment: 'pʰ w'
- following_context: ''
  preceding_context: ''
  replacement: 'pʷ'
  segment: 'p w'
- following_context: ''
  preceding_context: ''
  replacement: 'tʷ'
  segment: 'tʰ w'
- following_context: ''
  preceding_context: ''
  replacement: 'tʷ'
  segment: 't w'
- following_context: ''
  preceding_context: ''
  replacement: 'kʷ'
  segment: 'kʰ w'
- following_context: ''
  preceding_context: ''
  replacement: 'kʷ'
  segment: 'k w'
