-
  - p
  - pʷ
  - pʰ
  - pʲ
-
  - b
  - bʲ
-
  - f
  - fʷ
  - fʲ
-
  - v
  - vʷ
  - vʲ
-
  - θ
-
  - ð
-
  - d̪
-
  - t̪
-
  - t
  - tʷ
  - tʰ
  - tʲ
-
  - d
  - dʲ
-
  - ɾ
  - ɾʲ
-
  - ʔ
-
  - tʃ
-
  - dʒ
-
  - ʃ
-
  - ʒ
-
  - s
-
  - z
-
  - ɹ
-
  - m
  - mʲ
  - m̩
  - ɱ
-
  - n
  - n̩
-
  - ɲ
-
  - ŋ
-
  - ɾ̃
-
  - l
-
  - ɫ
  - ɫ̩
-
  - ʎ
-
  - ɟ
  - ɡ
-
  - c
  - cʷ
  - cʰ
  - k
  - kʷ
  - kʰ
-
  - ç
  - h
-
  - ɐ
-
  - ə
-
  - ɜː
  - ɜ
-
  - ɝ
-
  - ɚ
-
  - ʊ
-
  - ɪ
-
  - ɑ
  - ɑː
-
  - ɒ
  - ɒː
  - ɔ
-
  - aː
  - a
-
  - aj
-
  - aw
-
  - i
  - iː
-
  - j
-
  - æ
-
  - ɛː
  - ɛ
-
  - e
  - ej
-
  - ʉ
  - ʉː
  - uː
  - u
-
  - w
-
  - ɔj
-
  - ow
  - əw
  - o
