-
  - b
-
  - d
-
  - dʒ
-
  - f
-
  - k
  - c
-
  - l
  - ʎ
-
  - m
  - mʲ
-
  - n
-
  - ɲ
-
  - p
-
  - s
-
  - t
-
  - ts
-
  - tʃ
-
  - v
-
  - ɟ
  - ɡ
-
  - ɥ
-
  - ʁ
-
  - ʃ
-
  - ʒ
-
  - z
-
  - ŋ
-
  - a
-
  - e
-
  - i
  - j
-
  - o
-
  - u
  - w
-
  - y
-
  - ø
-
  - œ
-
  - ɑ
-
  - ɑ̃
-
  - ɔ
-
  - ɔ̃
-
  - ə
-
  - ɛ
-
  - ɛ̃
