-
  - a
  - aː
-
  - aj
-
  - aw
-
  - b
-
  - d
-
  - eː
-
  - f
-
  - iː
-
  - j
-
  - c
  - cʰ
  - k
  - kʰ
-
  - l
  - l̩
-
  - m
  - m̩
-
  - n
  - n̩
  - ɲ
-
  - oː
-
  - p
  - pʰ
-
  - pf
-
  - s
-
  - t
  - tʰ
-
  - ts
-
  - tʃ
-
  - uː
-
  - v
-
  - h
  - x
  - ç
-
  - yː
-
  - z
-
  - øː
-
  - ŋ
-
  - œ
-
  - ɔ
-
  - ɔʏ
-
  - ə
-
  - ɛ
-
  - ɟ
  - ɡ
-
  - ɪ
-
  - ɐ
  - ʁ
-
  - ʃ
-
  - ʊ
-
  - ʏ
