-
  - p
  - pː
-
  - pʲ
  - pʲː
-
  - b
  - bː
  - v
  - vː
-
  - bʲ
  - bʲː
  - vʲ
  - vʲː
-
  - t
  - tː
  - tʲ
  - tʲː
-
  - d
  - dː
  - dʲ
  - dʲː
-
  - tɕ
  - tɕː
-
  - ɕ
  - ɕː
-
  - s
  - sː
-
  - ts
  - tsː
-
  - z
  - dz
  - dzː
-
  - dʑ
  - dʑː
  - ʑ
-
  - ɾ
  - ɾː
-
  - ɾʲ
  - ɾʲː
-
  - ɴ
  - ɴː
-
  - m
  - mː
-
  - mʲ
  - mʲː
-
  - n
  - nː
-
  - ɲ
  - ɲː
-
  - ŋ
-
  - ɰ̃
-
  - ɟ
  - ɟː
-
  - ɡ
  - ɡː
-
  - c
  - cː
-
  - k
  - kː
-
  - ç
  - çː
  - h
  - hː
  - ɸ
  - ɸː
  - ɸʲ
  - ɸʲː
-
  - aː
  - a
-
  - i
  - iː
-
  - i̥
-
  - j
-
  - e
  - eː
-
  - ɯ
  - ɯː
-
  - ɯ̥
-
  - ɨ
  - ɨː
-
  - ɨ̥
-
  - w
-
  - o
  - oː
-
  - ʔ
