-
  - b
  - bː
-
  - bʲ
  - bʲː
-
  - d̪
  - d̪ː
-
  - dʲ
  - dʲː
-
  - f
  - fː
-
  - fʲ
  - fʲː
-
  - j
  - jː
-
  - k
  - kː
-
  - c
  - cː
-
  - m
  - mː
-
  - mʲ
  - mʲː
-
  - n̪
  - n̪ː
-
  - ɲ
  - ɲː
-
  - p
  - pː
-
  - pʲ
  - pʲː
-
  - r
  - rː
-
  - rʲ
  - rʲː
-
  - s̪
  - s̪ː
-
  - sʲ
  - sʲː
-
  - tɕ
  - tɕː
-
  - tʂ
  - tʂː
  - dʐː
-
  - t̪
  - t̪ː
-
  - tʲ
  - tʲː
-
  - t̪s̪
  - t̪s̪ː
  - d̪z̪
  - d̪z̪ː
-
  - tsʲ
  - dzʲː
-
  - v
  - vː
-
  - vʲ
  - vʲː
-
  - ç
-
  - x
  - xː
  - ɣ
-
  - z̪
  - z̪ː
-
  - zʲ
  - zʲː
-
  - ɕː
-
  - ɟ
  - ɟː
-
  - ɡ
  - ɡː
-
  - ɫ
  - ɫː
-
  - ʎ
  - ʎː
-
  - ʂ
  - ʂː
-
  - ʐ
  - ʐː
  - ʑː
-
  - a
-
  - æ
-
  - ɐ
-
  - ə
-
  - ɛ
-
  - e
-
  - i
-
  - ɪ
-
  - ɨ
-
  - ɵ
-
  - o
-
  - u
-
  - ʉ
-
  - ʊ
