-
  - b
-
  - d̪
-
  - f
-
  - h
-
  - j
-
  - k
  - kʰ
-
  - l̪
-
  - m
-
  - n̪
-
  - p
  - pʰ
-
  - r
-
  - s̪
-
  - t̪
  - t̪ʰ
-
  - ŋ
-
  - ɕ
-
  - ɖ
-
  - ɡ
-
  - ɧ
-
  - ɭ
-
  - ɳ
-
  - ʂ
-
  - ʈ
  - ʈʰ
-
  - ʋ
-
  - a
  - a˥˧
  - a˥˩
  - a˧˩
  - a˩
-
  - eː
  - eː˥˧
  - eː˥˩
  - eː˧˩
  - eː˩
-
  - iː
  - iː˥˧
  - iː˥˩
  - iː˧˩
-
  - oː
  - oː˥˧
  - oː˥˩
  - oː˧˩
  - oː˩
-
  - uː
  - uː˥˧
  - uː˥˩
  - uː˧˩
-
  - yː
  - yː˥˧
  - yː˥˩
  - yː˧˩
  - yː˩
-
  - øː
  - øː˥˧
  - øː˥˩
  - øː˧˩
  - øː˩
-
  - œ
  - œ˥˩
  - œ˧˩
-
  - ɑː
  - ɑː˥˧
  - ɑː˥˩
  - ɑː˧˩
  - ɑː˩
-
  - ɔ
  - ɔ˥˧
  - ɔ˥˩
  - ɔ˧˩
  - ɔ˩
-
  - ɛ
  - ɛː
  - ɛː˥˧
  - ɛː˥˩
  - ɛː˧˩
  - ɛ˥˧
  - ɛ˥˩
  - ɛ˧˩
  - ɛ˩
-
  - ɪ
  - ɪ˥˧
  - ɪ˥˩
  - ɪ˧˩
  - ɪ˩
-
  - ɵ
  - ɵ˥˧
  - ɵ˥˩
  - ɵ˧˩
  - ɵ˩
-
  - ʉː
  - ʉː˥˧
  - ʉː˥˩
  - ʉː˧˩
-
  - ʊ
  - ʊ˥˩
  - ʊ˧˩
  - ʊ˩
-
  - ʏ
  - ʏ˥˧
  - ʏ˥˩
  - ʏ˧˩
  - ʏ˩
