-
  - a
  - aː
-
  - b
  - bː
-
  - c
  - cː
  - k
  - kː
-
  - dʒ
  - dʒː
-
  - d̪
  - d̪ː
-
  - e
  - eː
  - ɛ
-
  - f
  - fː
-
  - h
  - hː
  - ç
  - çː
-
  - i
  - iː
  - ɪ
-
  - j
  - jː
-
  - m
  - mː
-
  - n̪
  - n̪ː
  - ɲ
-
  - o
  - oː
-
  - p
  - pː
-
  - s̪
  - s̪ː
-
  - tʃ
  - tʃː
-
  - t̪
  - t̪ː
-
  - u
  - uː
  - ʊ
-
  - v
  - vː
-
  - y
  - yː
  - ʏ
-
  - z̪
  - z̪ː
-
  - ø
  - øː
  - œ
-
  - ŋ
-
  - ɟ
  - ɟː
  - ɡ
  - ɡː
-
  - ɫ
  - ɫː
  - ʎ
  - ʎː
-
  - ɯ
  - ɯː
  - ɨ
-
  - ɾ
  - ɾː
-
  - ʃ
  - ʃː
-
  - ʒ
