-
  - b
  - bʲ
  - bʲː
  - bː
-
  - c
  - cː
  - k
  - kː
-
  - ɡ
  - ɟ
  - ɡː
-
  - dzʲ
  - dʒ
-
  - dʲ
  - dʲː
  - d̪
  - d̪ː
-
  - d̪z̪
  - d̪z̪ː
-
  - f
  - fː
  - fʲ
-
  - j
-
  - l
  - lː
  - ʎ
  - ʎː
-
  - m
  - mː
  - mʲ
  - mʲː
-
  - n̪
  - n̪ː
  - ɲ
  - ɲː
-
  - p
  - pʲ
  - pʲː
-
  - sʲ
  - sʲː
  - s̪
  - s̪ː
-
  - tsʲ
  - tsʲː
  - t̪s̪
  - t̪s̪ː
-
  - tʃ
  - tʃʲ
  - tʃʲː
  - tʃː
-
  - tʲ
  - tʲː
  - t̪
  - t̪ː
-
  - x
  - ç
-
  - ɦ
  - ɦː
  - ʝ
-
  - zʲ
  - zʲː
  - z̪
  - z̪ː
-
  - ɾ
  - ɾʲ
  - ɾʲː
  - ɾː
-
  - ʒ
  - ʒʲ
  - ʒʲː
-
  - ʃ
  - ʃʲ
  - ʃʲː
-
  - ʋ
  - ʋʲ
  - ʋʲː
  - ʋː
-
  - ɐ
  - ɑ
-
  - e
-
  - i
  - iː
-
  - o
  - ɔ
-
  - ɛ
-
  - ɪ
-
  - ʊ
  - u
