-
  - aː˦˥
  - aː˨ˀ˥
  - aː˨˦
  - aː˨˨
  - aː˨˩
  - aː˨˩ˀ
  - aː˨˩˦
  - aː˨˩˨
  - a˦˥
  - a˨ˀ˥
  - a˨˦
  - a˨˨
  - a˨˩
  - a˨˩ˀ
  - a˨˩˦
  - a˨˩˨
-
  - eː˦˥
  - eː˨ˀ˥
  - eː˨˦
  - eː˨˨
  - eː˨˩
  - eː˨˩ˀ
  - eː˨˩˦
  - eː˨˩˨
  - e˦˥
  - e˨ˀ˥
  - e˨˨
  - e˨˩
  - e˨˩ˀ
  - e˨˩˨
-
  - f
-
  - h
-
  - iə˦˥
  - iə˨ˀ˥
  - iə˨˦
  - iə˨˨
  - iə˨˩
  - iə˨˩ˀ
  - iə˨˩˦
  - iə˨˩˨
-
  - iː˦˥
  - iː˨ˀ˥
  - iː˨˦
  - iː˨˨
  - iː˨˩
  - iː˨˩ˀ
  - iː˨˩˦
  - iː˨˩˨
  - i˦˥
  - i˨ˀ˥
  - i˨˦
  - i˨˨
  - i˨˩
  - i˨˩ˀ
  - i˨˩˦
  - i˨˩˨
-
  - j
-
  - k
  - k̚
  - c
-
  - l
-
  - m
-
  - n
-
  - oː˦˥
  - oː˨ˀ˥
  - oː˨˦
  - oː˨˨
  - oː˨˩
  - oː˨˩ˀ
  - oː˨˩˦
  - oː˨˩˨
  - o˦˥
  - o˨ˀ˥
  - o˨˦
  - o˨˨
  - o˨˩
  - o˨˩ˀ
  - o˨˩˦
  - o˨˩˨
-
  - p
  - p̚
  - kp
-
  - r
-
  - s
-
  - t
  - t̚
-
  - tɕ
-
  - tʰ
-
  - uə˦˥
  - uə˨ˀ˥
  - uə˨˦
  - uə˨˨
  - uə˨˩
  - uə˨˩ˀ
  - uə˨˩˦
  - uə˨˩˨
-
  - uː˦˥
  - uː˨ˀ˥
  - uː˨˦
  - uː˨˨
  - uː˨˩
  - uː˨˩ˀ
  - uː˨˩˦
  - uː˨˩˨
  - u˦˥
  - u˨ˀ˥
  - u˨˦
  - u˨˨
  - u˨˩
  - u˨˩ˀ
  - u˨˩˦
  - u˨˩˨
-
  - v
-
  - w
-
  - x
-
  - z
-
  - ŋ
  - ɲ
  - ŋm
-
  - ɓ
-
  - ɔː˦˥
  - ɔː˨ˀ˥
  - ɔː˨˦
  - ɔː˨˨
  - ɔː˨˩
  - ɔː˨˩ˀ
  - ɔː˨˩˦
  - ɔː˨˩˨
  - ɔ˦˥
  - ɔ˨ˀ˥
  - ɔ˨˦
  - ɔ˨˨
  - ɔ˨˩
  - ɔ˨˩ˀ
  - ɔ˨˩˦
  - ɔ˨˩˨
-
  - ɗ
-
  - əː˦˥
  - əː˨ˀ˥
  - əː˨˦
  - əː˨˨
  - əː˨˩
  - əː˨˩ˀ
  - əː˨˩˦
  - əː˨˩˨
  - ə˦˥
  - ə˨ˀ˥
  - ə˨˦
  - ə˨˨
  - ə˨˩
  - ə˨˩ˀ
  - ə˨˩˦
  - ə˨˩˨
-
  - ɛː˦˥
  - ɛː˨ˀ˥
  - ɛː˨˦
  - ɛː˨˨
  - ɛː˨˩
  - ɛː˨˩ˀ
  - ɛː˨˩˦
  - ɛː˨˩˨
-
  - ɡ
  - ɣ
-
  - ɨə˦˥
  - ɨə˨ˀ˥
  - ɨə˨˦
  - ɨə˨˨
  - ɨə˨˩
  - ɨə˨˩ˀ
  - ɨə˨˩˦
  - ɨə˨˩˨
-
  - ɨː˦˥
  - ɨː˨ˀ˥
  - ɨː˨˦
  - ɨː˨˨
  - ɨː˨˩
  - ɨː˨˩ˀ
  - ɨː˨˩˦
  - ɨː˨˩˨
  - ɨ˦˥
  - ɨ˨ˀ˥
  - ɨ˨˦
  - ɨ˨˨
  - ɨ˨˩
  - ɨ˨˩ˀ
  - ɨ˨˩˦
  - ɨ˨˩˨
-
  - ʈ
-
  - ʔ
